### ISSUE TITLE
(not-an-issue) Curious about your experience

### ISSUE THREAD

**Issue by tennox** [johnae/devsh#1]
I stumbled over this after reading posts [like](https://hackernoon.com/configuration-files-suck-6daa9812f601) [these](https://matt-rickard.com/advanced-configuration-languages-are-wrong), and love the idea of just staying with nix and ditch the TOML.

I'm curious about how your experiment continued? :thinking: 
Did you like it? Did you find disadvantages?

**Comment by johnae** [comment]
Yeah I stopped using this in favor of https://github.com/numtide/devshell - that project has more people behind it and is used by many. It can also use just nix rather than toml.

Interesting that you found this project though 😀. As you can see it's been a while since the last commit.
